import type { Level, Params } from '@/sim/params';

/** Visibility rules shared by fields and groups. */
interface Visibility {
  levels?: Level[];
  /** Extra condition, e.g. "only while this controller is selected". */
  when?: (p: Params) => boolean;
}

/**
 * Declarative description of every tunable parameter. The parameter panel is generated from this,
 * and the short `help` texts are the in-app explanations (docs/ui-and-visualization.md §4).
 */
export type Field = Visibility &
  (
    | {
        kind: 'number';
        path: string;
        label: string;
        unit?: string;
        min: number;
        max: number;
        step: number;
        log?: boolean;
        help?: string;
      }
    | { kind: 'bool'; path: string; label: string; help?: string }
    | {
        kind: 'select';
        path: string;
        label: string;
        /** Options may be limited to some levels. */
        options: { value: string; label: string; levels?: Level[] }[];
        help?: string;
      }
  );

export interface Group extends Visibility {
  id: string;
  title: string;
  fields: Field[];
  /** Colour hint for PID groups: shows which loop this is. */
  loop?: string;
}

/** Whether a field or group is shown for these parameters. */
export const visible = (v: Visibility, p: Params): boolean =>
  (!v.levels || v.levels.includes(p.sim.level)) && (!v.when || v.when(p));

const l1Pid = (p: Params) => p.sim.level === 2 || p.control.l1.kind === 'pid';
const l1Is = (kind: Params['control']['l1']['kind']) => (p: Params) => p.control.l1.kind === kind;

/** Settings every L1 controller shares (repeated in each controller's group). */
const l1Common: Field[] = [
  {
    kind: 'bool',
    path: 'control.feedforward',
    label: 'Gravity feedforward',
    help: 'Add the thrust needed to hover (m̂·g) directly; the controller then only fights deviations.',
  },
  {
    kind: 'number',
    path: 'control.model.mass',
    label: 'Assumed mass m̂',
    unit: 'kg',
    min: 0.2,
    max: 3,
    step: 0.01,
    help: 'What the controller believes the mass is. Model-based controllers use it everywhere, not just in the feedforward.',
  },
  {
    kind: 'number',
    path: 'control.rateHz',
    label: 'Controller rate',
    unit: 'Hz',
    min: 2,
    max: 1000,
    step: 1,
    log: true,
  },
];
const l3Outer = (p: Params) => p.control.l3.outer === 'pid-cascade';
const l3Inner = (p: Params) => p.control.l3.inner === 'pid';

const pid = (
  prefix: string,
  opts: {
    kp: [number, number];
    ki: [number, number];
    kd: [number, number];
    unit?: string;
    levels?: Level[];
  },
): Field[] => [
  {
    kind: 'number',
    path: `${prefix}.kp`,
    label: 'Kp',
    min: opts.kp[0],
    max: opts.kp[1],
    step: 0.01,
    log: true,
    help: 'Proportional gain — reacts to where you are. Higher: stiffer and faster, but more overshoot and eventually oscillation.',
  },
  {
    kind: 'number',
    path: `${prefix}.ki`,
    label: 'Ki',
    min: opts.ki[0],
    max: opts.ki[1],
    step: 0.01,
    log: true,
    help: 'Integral gain — reacts to where you have been. Removes steady-state error (constant loads like gravity or steady wind), adds overshoot.',
  },
  {
    kind: 'number',
    path: `${prefix}.kd`,
    label: 'Kd',
    min: opts.kd[0],
    max: opts.kd[1],
    step: 0.01,
    log: true,
    help: 'Derivative gain — reacts to where you are going. Damps motion like a shock absorber; amplifies sensor noise.',
  },
  {
    kind: 'bool',
    path: `${prefix}.pOn`,
    label: 'P term',
    help: 'Switch the proportional term on/off.',
  },
  {
    kind: 'bool',
    path: `${prefix}.iOn`,
    label: 'I term',
    help: 'Switch the integral term on/off (clears the integral).',
  },
  {
    kind: 'bool',
    path: `${prefix}.dOn`,
    label: 'D term',
    help: 'Switch the derivative term on/off.',
  },
  {
    kind: 'select',
    path: `${prefix}.derivativeOn`,
    label: 'D acts on',
    options: [
      { value: 'measurement', label: 'measurement' },
      { value: 'error', label: 'error' },
    ],
    help: 'Differentiating the error makes the D term spike on every setpoint step ("derivative kick"). Differentiating the measurement gives the same damping without the kick.',
  },
  {
    kind: 'number',
    path: `${prefix}.dFilterHz`,
    label: 'D filter',
    unit: 'Hz',
    min: 0,
    max: 200,
    step: 0.5,
    help: 'Low-pass cutoff on the derivative. Lower = smoother but more lag. 0 = no filter.',
  },
  {
    kind: 'select',
    path: `${prefix}.antiWindup`,
    label: 'Anti-windup',
    options: [
      { value: 'none', label: 'none' },
      { value: 'clamp', label: 'conditional integration' },
      { value: 'integral-limit', label: 'integral limit' },
      { value: 'back-calculation', label: 'back-calculation' },
    ],
    help: 'What to do with the integral while the actuator is saturated. Without protection it keeps growing ("winds up") and causes a big overshoot later.',
  },
  {
    kind: 'number',
    path: `${prefix}.iLimit`,
    label: 'I limit',
    unit: opts.unit,
    min: 0,
    max: 50,
    step: 0.1,
    help: 'Maximum |I| for the "integral limit" anti-windup strategy.',
  },
  {
    kind: 'number',
    path: `${prefix}.kb`,
    label: 'Kb',
    unit: '1/s',
    min: 0,
    max: 50,
    step: 0.1,
    help: 'Tracking gain of back-calculation anti-windup: how fast the integral is bled off during saturation.',
  },
];

const L12: Level[] = [1, 2];

export const SCHEMA: Group[] = [
  {
    id: 'controller',
    title: 'Controller',
    fields: [
      {
        kind: 'select',
        path: 'control.l1.kind',
        label: 'Altitude controller',
        options: [
          { value: 'pid', label: 'PID' },
          { value: 'lqr', label: 'LQR / LQI' },
          { value: 'adrc', label: 'ADRC' },
          { value: 'mpc', label: 'MPC' },
          { value: 'l1ac', label: 'L1 adaptive' },
        ],
        levels: [1],
        help: 'Which control law flies the drone. PID: three hand-tuned gains. LQR: gains computed from a model and a cost. ADRC: an observer estimates everything the model misses and cancels it.',
      },
      {
        kind: 'select',
        path: 'control.l1.estimator',
        label: 'State estimate',
        options: [
          { value: 'none', label: 'raw sensors' },
          { value: 'kalman', label: 'Kalman filter' },
        ],
        levels: [1],
        help: 'What the controller reads. Raw: the (noisy, slow) position sensor and velocity sensor directly. Kalman: a filter fusing the accelerometer with the position fixes.',
      },
      {
        kind: 'select',
        path: 'control.l3.outer',
        label: 'Outer stage',
        options: [
          { value: 'pid-cascade', label: 'PID cascade' },
          { value: 'geometric', label: 'geometric tracking (Lee)' },
          { value: 'mpc', label: 'MPC (linear, point mass)' },
          { value: 'mppi', label: 'MPPI (sampling)' },
          { value: 'policy', label: 'neural network policy' },
        ],
        levels: [3],
        help: 'Turns the position reference into a desired acceleration (thrust vector). The geometric controller also uses the reference’s velocity and acceleration (and its jerk for body-rate feedforward) when flying a trajectory.',
      },
      {
        kind: 'select',
        path: 'control.l3.attitude',
        label: 'Attitude law',
        options: [
          { value: 'quaternion', label: 'quaternion error' },
          { value: 'tilt', label: 'tilt-prioritised' },
          { value: 'euler', label: 'Euler angles (naive)' },
        ],
        levels: [3],
        help: 'How an attitude error becomes a body-rate command. Quaternion: the shortest rotation. Tilt-prioritised: fix the thrust direction first, yaw separately. Euler angles: subtract roll/pitch/yaw — fine when small, wrong near ±90° pitch.',
      },
      {
        kind: 'select',
        path: 'control.l3.inner',
        label: 'Inner stage',
        options: [
          { value: 'pid', label: 'attitude P + rate PID' },
          { value: 'indi', label: 'attitude P + rate INDI' },
        ],
        levels: [3],
        help: 'Turns the desired attitude into motor torques. INDI measures the angular acceleration its torque produces and corrects only the difference, so unmodelled torques (a damaged prop) are rejected at once.',
      },
      {
        kind: 'select',
        path: 'control.l3.compensation',
        label: 'Disturbance compensation',
        options: [
          { value: 'none', label: 'none (m̂·a model)' },
          { value: 'indi', label: 'acceleration INDI' },
          { value: 'l1ac', label: 'L1 adaptive' },
          { value: 'learned', label: 'learned residual model' },
        ],
        levels: [3],
        help: 'How a desired acceleration becomes a thrust vector. Acceleration INDI keeps the thrust the motors produce now and corrects it by the acceleration the accelerometer says is missing — gusts are felt before they cause a position error.',
      },
      {
        kind: 'select',
        path: 'control.l3.safety',
        label: 'Safety filter',
        options: [
          { value: 'none', label: 'none' },
          { value: 'cbf', label: 'control barrier function' },
        ],
        levels: [3],
        help: 'Changes the desired acceleration as little as possible so that the drone stays out of the keep-out zones — whatever the controller above wants.',
      },
    ],
  },
  {
    id: 'setpoint',
    title: 'Setpoint',
    fields: [
      {
        kind: 'number',
        path: 'setpoint.y',
        label: 'Altitude',
        unit: 'm',
        min: 0.2,
        max: 10,
        step: 0.05,
        help: 'Target height of the centre of mass above the floor. Keys ↑/↓ change it by 0.1 m (Shift: 1 m).',
      },
      {
        kind: 'number',
        path: 'setpoint.x',
        label: 'X',
        unit: 'm',
        min: -10,
        max: 10,
        step: 0.05,
        levels: [2, 3],
      },
      {
        kind: 'number',
        path: 'setpoint.z',
        label: 'Z',
        unit: 'm',
        min: -10,
        max: 10,
        step: 0.05,
        levels: [2, 3],
      },
      {
        kind: 'number',
        path: 'setpoint.yawDeg',
        label: 'Yaw',
        unit: '°',
        min: -180,
        max: 180,
        step: 1,
        levels: [3],
      },
      {
        kind: 'number',
        path: 'setpoint.rateLimit',
        label: 'Rate limit',
        unit: 'm/s',
        min: 0,
        max: 5,
        step: 0.05,
        help: 'Move the setpoint gradually instead of jumping. 0 = instant steps (best for studying step responses).',
      },
      {
        kind: 'select',
        path: 'setpoint.profile',
        label: 'Automatic motion',
        options: [
          { value: 'none', label: 'none' },
          { value: 'square', label: 'square wave (steps)' },
          { value: 'sine', label: 'sine' },
          { value: 'triangle', label: 'triangle (ramps)' },
          { value: 'circle', label: 'circle', levels: [2, 3] },
          { value: 'figure8', label: 'figure-8', levels: [2, 3] },
          { value: 'corners', label: 'square: steps to each corner', levels: [2, 3] },
          { value: 'minsnap', label: 'square: min-snap trajectory', levels: [2, 3] },
        ],
        help: 'Move the setpoint automatically around its base value. Square = repeated step responses; sine = how well the loop follows a smooth motion (try shortening the period). Circle, figure-8 and the square paths fly in the horizontal plane; amplitude = radius or half the side, period = one lap.',
      },
      {
        kind: 'select',
        path: 'setpoint.profileAxis',
        label: 'Motion axis',
        when: (p) => ['square', 'sine', 'triangle'].includes(p.setpoint.profile),
        options: [
          { value: 'y', label: 'altitude (Y)' },
          { value: 'x', label: 'horizontal (X)' },
        ],
        levels: [2, 3],
      },
      {
        kind: 'number',
        path: 'setpoint.profileAmplitude',
        label: 'Amplitude',
        unit: 'm',
        min: 0.05,
        max: 3,
        step: 0.05,
      },
      {
        kind: 'number',
        path: 'setpoint.profilePeriod',
        label: 'Period',
        unit: 's',
        min: 0.5,
        max: 30,
        step: 0.1,
        log: true,
      },
    ],
  },
  {
    id: 'alt',
    title: 'Altitude PID',
    loop: 'alt',
    levels: L12,
    when: l1Pid,
    fields: [
      {
        kind: 'bool',
        path: 'control.feedforward',
        label: 'Gravity feedforward',
        help: 'Add the thrust needed to hover (m̂·g) directly. The PID then only fights deviations. Turn it off to see the "gravity droop" of a P controller.',
      },
      {
        kind: 'number',
        path: 'control.model.mass',
        label: 'Assumed mass m̂',
        unit: 'kg',
        min: 0.2,
        max: 3,
        step: 0.01,
        help: 'What the controller believes the mass is (used by the feedforward). A wrong value leaves an error only the I term can remove.',
      },
      {
        kind: 'number',
        path: 'control.rateHz',
        label: 'Controller rate',
        unit: 'Hz',
        min: 2,
        max: 1000,
        step: 1,
        log: true,
        help: 'How often the controller samples the sensor and updates its output. Too slow → delay → oscillation → instability.',
      },
      ...pid('control.alt', { kp: [0.1, 200], ki: [0.01, 100], kd: [0.01, 100], unit: 'N' }),
    ],
  },
  {
    id: 'lqr',
    title: 'LQR',
    loop: 'alt',
    levels: [1],
    when: l1Is('lqr'),
    fields: [
      {
        kind: 'number',
        path: 'control.lqr.qPos',
        label: 'Cost of position error q_e',
        min: 0.1,
        max: 10000,
        step: 0.1,
        log: true,
        help: 'How much you hate being away from the setpoint (per m²). Higher → stiffer, faster.',
      },
      {
        kind: 'number',
        path: 'control.lqr.qVel',
        label: 'Cost of velocity q_v',
        min: 0.01,
        max: 1000,
        step: 0.01,
        log: true,
        help: 'How much you hate moving fast (per (m/s)²). Higher → more damping, calmer.',
      },
      {
        kind: 'number',
        path: 'control.lqr.r',
        label: 'Cost of thrust r',
        min: 0.01,
        max: 100,
        step: 0.01,
        log: true,
        help: 'How much you hate using the motors (per N²). Higher → gentler, slower, less thrust.',
      },
      {
        kind: 'bool',
        path: 'control.lqr.integral',
        label: 'Integral state (LQI)',
        help: 'Add ∫e as a fourth state with its own cost: the optimal-control way to get integral action.',
      },
      {
        kind: 'number',
        path: 'control.lqr.qInt',
        label: 'Cost of ∫e q_i',
        min: 0.1,
        max: 1000,
        step: 0.1,
        log: true,
        help: 'How much you hate an error that persists. Higher → faster removal of offsets, more overshoot.',
      },
      {
        kind: 'bool',
        path: 'control.lqr.lagState',
        label: 'Model the motor lag',
        help: 'Add the actual thrust as a state (from motor telemetry, or a model of the motors if there is none).',
      },
      {
        kind: 'number',
        path: 'control.model.motorTau',
        label: 'Assumed motor τ',
        unit: 's',
        min: 0.001,
        max: 0.3,
        step: 0.001,
        log: true,
        help: 'The motor time constant the model assumes.',
      },
      ...l1Common,
    ],
  },
  {
    id: 'adrc',
    title: 'ADRC',
    loop: 'alt',
    levels: [1],
    when: l1Is('adrc'),
    fields: [
      {
        kind: 'number',
        path: 'control.adrc.wc',
        label: 'Controller bandwidth ω_c',
        unit: 'rad/s',
        min: 0.5,
        max: 20,
        step: 0.1,
        log: true,
        help: 'How fast the (disturbance-free) loop should respond. Both closed-loop poles sit at −ω_c: critically damped by construction.',
      },
      {
        kind: 'number',
        path: 'control.adrc.wo',
        label: 'Observer bandwidth ω_o',
        unit: 'rad/s',
        min: 1,
        max: 200,
        step: 0.5,
        log: true,
        help: 'How fast the observer believes the sensor. Higher: disturbances are estimated sooner — and sensor noise goes straight into the motors.',
      },
      ...l1Common,
    ],
  },
  {
    id: 'kalman',
    title: 'Kalman filter',
    levels: [1],
    when: (p) => p.control.l1.estimator === 'kalman',
    fields: [
      {
        kind: 'number',
        path: 'control.kalman.accSigma',
        label: 'Assumed accelerometer σ',
        unit: 'm/s²',
        min: 0.01,
        max: 10,
        step: 0.01,
        log: true,
        help: 'Process noise: how much the filter distrusts its prediction. Higher → follows the position sensor more.',
      },
      {
        kind: 'number',
        path: 'control.kalman.posSigma',
        label: 'Assumed position σ',
        unit: 'm',
        min: 0.001,
        max: 1,
        step: 0.001,
        log: true,
        help: 'Measurement noise: how much the filter distrusts the position sensor. Higher → smoother, but slower to notice real changes.',
      },
      {
        kind: 'number',
        path: 'control.kalman.biasSigma',
        label: 'Bias drift',
        unit: 'm/s²/√s',
        min: 0,
        max: 1,
        step: 0.001,
        help: 'How fast the filter lets its accelerometer-bias estimate move. 0 = the bias is assumed constant (and never learnt).',
      },
      {
        kind: 'bool',
        path: 'control.kalman.altBiasState',
        label: 'Altimeter-bias state',
        help: "Adds the altimeter's own offset as a fourth state. The altimeter reads altitude plus offset, so the two cannot be told apart: the filter cannot estimate it, but it stops pretending to know the altitude better than it does.",
      },
      {
        kind: 'number',
        path: 'control.kalman.altBiasSigma',
        label: 'Altimeter-bias prior σ',
        unit: 'm',
        min: 0.01,
        max: 2,
        step: 0.01,
        when: (p) => p.control.kalman.altBiasState,
        help: 'How large the altimeter offset might be, before any measurement. Since no measurement can reduce it, this is also what the filter believes about it for ever.',
      },
    ],
  },
  {
    id: 'posH',
    title: 'Horizontal PID (X, Z)',
    loop: 'pos.x',
    levels: [2],
    fields: [
      {
        kind: 'number',
        path: 'control.maxHForce',
        label: 'Max horizontal force',
        unit: 'N',
        min: 0.5,
        max: 20,
        step: 0.1,
      },
      ...pid('control.posH', { kp: [0.1, 100], ki: [0.01, 50], kd: [0.01, 50], unit: 'N' }),
    ],
  },
  {
    id: 'geometric',
    title: 'Geometric tracking',
    loop: 'pos.x',
    levels: [3],
    when: (p) => p.control.l3.outer === 'geometric',
    fields: [
      {
        kind: 'number',
        path: 'control.geometric.kp',
        label: 'Kp (position)',
        unit: '1/s²',
        min: 0.1,
        max: 100,
        step: 0.1,
        log: true,
        help: 'a = a_ref − Kp·e_p − Kv·e_v − Ki·∫e_p: acceleration per metre of position error.',
      },
      {
        kind: 'number',
        path: 'control.geometric.kv',
        label: 'Kv (velocity)',
        unit: '1/s',
        min: 0.1,
        max: 50,
        step: 0.1,
        log: true,
        help: 'Acceleration per m/s of velocity error: the damping.',
      },
      {
        kind: 'number',
        path: 'control.geometric.ki',
        label: 'Ki (integral)',
        unit: '1/s³',
        min: 0,
        max: 10,
        step: 0.05,
        help: 'Removes steady offsets (wind). Bypassed when acceleration INDI is on.',
      },
      {
        kind: 'bool',
        path: 'control.geometric.feedforward',
        label: 'Trajectory feedforward',
        help: 'Use the reference’s velocity and acceleration, and turn its jerk into body-rate feedforward (differential flatness). Off: pure feedback, which can only react once an error exists.',
      },
    ],
  },
  {
    id: 'l3pos',
    title: 'Position P',
    loop: 'pos.x',
    levels: [3],
    when: l3Outer,
    fields: [
      {
        kind: 'number',
        path: 'control.l3.posKpH',
        label: 'Kp horizontal',
        unit: '1/s',
        min: 0.05,
        max: 10,
        step: 0.01,
        log: true,
        help: 'Position error (m) → velocity setpoint (m/s). Pure P is enough: the velocity loop below provides integral action.',
      },
      {
        kind: 'number',
        path: 'control.l3.posKpV',
        label: 'Kp vertical',
        unit: '1/s',
        min: 0.05,
        max: 10,
        step: 0.01,
        log: true,
      },
      {
        kind: 'number',
        path: 'control.l3.vMaxH',
        label: 'Max horiz. speed',
        unit: 'm/s',
        min: 0.2,
        max: 15,
        step: 0.1,
      },
      {
        kind: 'number',
        path: 'control.l3.vMaxV',
        label: 'Max vert. speed',
        unit: 'm/s',
        min: 0.2,
        max: 8,
        step: 0.1,
      },
      {
        kind: 'number',
        path: 'control.l3.hzPos',
        label: 'Loop rate',
        unit: 'Hz',
        min: 1,
        max: 1000,
        step: 1,
        log: true,
      },
    ],
  },
  {
    id: 'l3velH',
    title: 'Velocity PID — horizontal',
    loop: 'vel.x',
    levels: [3],
    when: l3Outer,
    fields: [
      {
        kind: 'number',
        path: 'control.l3.maxTiltDeg',
        label: 'Max tilt',
        unit: '°',
        min: 5,
        max: 60,
        step: 1,
        help: 'The drone accelerates sideways by tilting; this caps how far.',
      },
      {
        kind: 'number',
        path: 'control.l3.hzVel',
        label: 'Loop rate',
        unit: 'Hz',
        min: 1,
        max: 1000,
        step: 1,
        log: true,
      },
      ...pid('control.l3.velH', { kp: [0.05, 50], ki: [0.01, 20], kd: [0.001, 10], unit: 'm/s²' }),
    ],
  },
  {
    id: 'l3velV',
    title: 'Velocity PID — vertical',
    loop: 'vel.y',
    levels: [3],
    when: l3Outer,
    fields: [
      { kind: 'bool', path: 'control.feedforward', label: 'Gravity feedforward' },
      {
        kind: 'number',
        path: 'control.model.mass',
        label: 'Assumed mass m̂',
        unit: 'kg',
        min: 0.2,
        max: 3,
        step: 0.01,
      },
      ...pid('control.l3.velV', { kp: [0.05, 50], ki: [0.01, 20], kd: [0.001, 10], unit: 'm/s²' }),
    ],
  },
  {
    id: 'l3att',
    title: 'Attitude P',
    loop: 'att.roll',
    levels: [3],
    fields: [
      {
        kind: 'number',
        path: 'control.l3.attKpRP',
        label: 'Kp roll/pitch',
        unit: '1/s',
        min: 0.5,
        max: 40,
        step: 0.1,
        log: true,
        help: 'Angle error (°) → body-rate setpoint (°/s).',
      },
      {
        kind: 'number',
        path: 'control.l3.attKpYaw',
        label: 'Kp yaw',
        unit: '1/s',
        min: 0.1,
        max: 20,
        step: 0.1,
        log: true,
      },
      {
        kind: 'number',
        path: 'control.l3.maxRateDeg',
        label: 'Max rate',
        unit: '°/s',
        min: 30,
        max: 1500,
        step: 10,
      },
      {
        kind: 'number',
        path: 'control.l3.hzAtt',
        label: 'Loop rate',
        unit: 'Hz',
        min: 1,
        max: 1000,
        step: 1,
        log: true,
        help: 'Make this slower than the velocity loop to see why inner loops must be faster than outer ones.',
      },
    ],
  },
  {
    id: 'l3rateRP',
    title: 'Rate PID — roll/pitch',
    loop: 'rate.roll',
    levels: [3],
    when: l3Inner,
    fields: [
      {
        kind: 'number',
        path: 'control.l3.hzRate',
        label: 'Loop rate',
        unit: 'Hz',
        min: 10,
        max: 1000,
        step: 1,
        log: true,
      },
      ...pid('control.l3.rateRP', {
        kp: [0.5, 200],
        ki: [0.01, 100],
        kd: [0.001, 5],
        unit: '°/s²',
      }),
    ],
  },
  {
    id: 'l3rateYaw',
    title: 'Rate PID — yaw',
    loop: 'rate.yaw',
    levels: [3],
    when: l3Inner,
    fields: [
      ...pid('control.l3.rateYaw', {
        kp: [0.5, 200],
        ki: [0.01, 100],
        kd: [0.001, 5],
        unit: '°/s²',
      }),
    ],
  },
  {
    id: 'physics',
    title: 'Physics',
    fields: [
      {
        kind: 'number',
        path: 'drone.mass',
        label: 'True mass',
        unit: 'kg',
        min: 0.3,
        max: 2.5,
        step: 0.01,
        help: 'The real mass. Change it mid-flight to simulate picking up or dropping a payload.',
      },
      {
        kind: 'number',
        path: 'drone.maxMotorThrust',
        label: 'Max thrust / motor',
        unit: 'N',
        min: 3,
        max: 15,
        step: 0.1,
        help: 'Actuator limit. Total available thrust is 4× this. Low values make saturation and windup easy to provoke.',
      },
      {
        kind: 'number',
        path: 'drone.motorTau',
        label: 'Motor time constant',
        unit: 's',
        min: 0.001,
        max: 0.3,
        step: 0.001,
        log: true,
        help: 'Motors need time to spin up (first-order lag). Lag limits how aggressive the gains can be.',
      },
      {
        kind: 'number',
        path: 'drone.dragV',
        label: 'Vertical drag',
        unit: 'N·s²/m²',
        min: 0,
        max: 2,
        step: 0.01,
        help: 'Quadratic air drag on vertical motion relative to the air. This is how vertical wind pushes the drone.',
      },
      {
        kind: 'number',
        path: 'drone.dragH',
        label: 'Horizontal drag',
        unit: 'N·s²/m²',
        min: 0,
        max: 2,
        step: 0.01,
        levels: [2, 3],
      },
    ],
  },
  {
    id: 'wind',
    title: 'Wind',
    fields: [
      { kind: 'bool', path: 'wind.enabled', label: 'Wind' },
      {
        kind: 'number',
        path: 'wind.meanSpeed',
        label: 'Mean speed',
        unit: 'm/s',
        min: 0,
        max: 15,
        step: 0.1,
        levels: [2, 3],
        help: 'A constant wind is a constant disturbance — exactly what the I term exists for.',
      },
      {
        kind: 'number',
        path: 'wind.meanHeading',
        label: 'Mean heading',
        unit: '°',
        min: 0,
        max: 360,
        step: 1,
        levels: [2, 3],
      },
      {
        kind: 'number',
        path: 'wind.meanVertical',
        label: 'Mean vertical',
        unit: 'm/s',
        min: -8,
        max: 8,
        step: 0.1,
        help: 'Steady updraft (+) or downdraft (−).',
      },
      {
        kind: 'number',
        path: 'wind.turbSigma',
        label: 'Turbulence σ',
        unit: 'm/s',
        min: 0,
        max: 5,
        step: 0.05,
        help: 'Intensity of continuous random fluctuation (Ornstein–Uhlenbeck process).',
      },
      {
        kind: 'number',
        path: 'wind.turbTau',
        label: 'Turbulence τ',
        unit: 's',
        min: 0.05,
        max: 10,
        step: 0.05,
        log: true,
        help: 'Correlation time. Small = jittery, large = slow wandering.',
      },
      { kind: 'bool', path: 'wind.gustsOn', label: 'Random gusts' },
      {
        kind: 'number',
        path: 'wind.gustsPerMinute',
        label: 'Gusts / minute',
        min: 0,
        max: 60,
        step: 0.5,
      },
      {
        kind: 'number',
        path: 'wind.gustAmpMin',
        label: 'Gust min',
        unit: 'm/s',
        min: 0,
        max: 20,
        step: 0.1,
      },
      {
        kind: 'number',
        path: 'wind.gustAmpMax',
        label: 'Gust max',
        unit: 'm/s',
        min: 0,
        max: 25,
        step: 0.1,
      },
      {
        kind: 'number',
        path: 'wind.gustDurMin',
        label: 'Gust min duration',
        unit: 's',
        min: 0.1,
        max: 10,
        step: 0.1,
      },
      {
        kind: 'number',
        path: 'wind.gustDurMax',
        label: 'Gust max duration',
        unit: 's',
        min: 0.1,
        max: 10,
        step: 0.1,
      },
      {
        kind: 'number',
        path: 'wind.gustVertical',
        label: 'Gust vertical share',
        min: 0,
        max: 1,
        step: 0.01,
        help: 'Vertical component of the gust direction. In the altitude-only level only this part matters.',
      },
    ],
  },
  {
    id: 'indi',
    title: 'INDI',
    loop: 'rate.roll',
    levels: [3],
    when: (p) => p.control.l3.inner === 'indi' || p.control.l3.compensation === 'indi',
    fields: [
      {
        kind: 'number',
        path: 'control.indi.rateKpRP',
        label: 'Rate gain roll/pitch',
        unit: '1/s',
        min: 1,
        max: 200,
        step: 0.5,
        log: true,
        when: (p) => p.control.l3.inner === 'indi',
        help: 'α_des = K·(ω_sp − ω): how hard to correct a body-rate error. The only tuning of the rate loop.',
      },
      {
        kind: 'number',
        path: 'control.indi.rateKpYaw',
        label: 'Rate gain yaw',
        unit: '1/s',
        min: 1,
        max: 100,
        step: 0.5,
        log: true,
        when: (p) => p.control.l3.inner === 'indi',
      },
      {
        kind: 'number',
        path: 'control.indi.filterHz',
        label: 'Gyro filter',
        unit: 'Hz',
        min: 1,
        max: 100,
        step: 0.5,
        log: true,
        when: (p) => p.control.l3.inner === 'indi',
        help: 'Low-pass on the gyro before differentiating it. Lower: less noise, more delay.',
      },
      {
        kind: 'number',
        path: 'control.indi.accFilterHz',
        label: 'Accelerometer filter',
        unit: 'Hz',
        min: 1,
        max: 100,
        step: 0.5,
        log: true,
        when: (p) => p.control.l3.compensation === 'indi',
      },
      {
        kind: 'bool',
        path: 'control.indi.syncFilters',
        label: 'Synchronised filters',
        help: 'Pass the motor signal through the same filter as the measurement, so both describe the same moment. INDI subtracts one from the other: if they are out of step, it chases a ghost.',
      },
      {
        kind: 'number',
        path: 'control.model.inertiaScale',
        label: 'Assumed inertia',
        unit: '× true',
        min: 0.2,
        max: 5,
        step: 0.01,
        log: true,
        help: 'The only model INDI needs is how much torque it takes to accelerate. A factor-2 error is tolerated; a factor 3 too big makes the loop too aggressive.',
      },
      {
        kind: 'number',
        path: 'control.model.motorTau',
        label: 'Assumed motor τ',
        unit: 's',
        min: 0.001,
        max: 0.3,
        step: 0.001,
        log: true,
        help: 'Used to estimate the rotor speed when there is no motor telemetry.',
      },
    ],
  },
  {
    id: 'l1ac',
    title: 'L1 adaptive',
    loop: 'alt',
    when: (p) =>
      (p.sim.level === 1 && p.control.l1.kind === 'l1ac') ||
      (p.sim.level === 3 && p.control.l3.compensation === 'l1ac'),
    fields: [
      {
        kind: 'number',
        path: 'control.l1ac.filterHz',
        label: 'Filter C(s)',
        unit: 'Hz',
        min: 0.2,
        max: 100,
        step: 0.1,
        log: true,
        help: 'How much of the adaptive estimate reaches the motors. The robustness knob: high lets noise through, low reacts late.',
      },
      {
        kind: 'number',
        path: 'control.l1ac.as',
        label: 'Predictor pole',
        unit: '1/s',
        min: 1,
        max: 200,
        step: 1,
        log: true,
        help: 'How fast the state predictor follows the measurement.',
      },
      {
        kind: 'number',
        path: 'control.l1ac.wc',
        label: 'Baseline bandwidth ω_c',
        unit: 'rad/s',
        min: 0.5,
        max: 20,
        step: 0.1,
        log: true,
        levels: [1],
      },
      ...l1Common.map((f): Field => ({ ...f, levels: [1] })),
    ],
  },
  {
    id: 'residual',
    title: 'Learned residual model',
    levels: [3],
    when: (p) => p.control.l3.compensation === 'learned',
    fields: [
      {
        kind: 'number',
        path: 'control.residual.forgetting',
        label: 'Forgetting λ',
        min: 0.9,
        max: 0.9999,
        step: 0.0001,
        help: 'Memory of the recursive least-squares fit (per 10 ms update). Closer to 1: longer memory, smoother, slower to follow a change of wind.',
      },
      {
        kind: 'number',
        path: 'control.residual.filterHz',
        label: 'Measurement filter',
        unit: 'Hz',
        min: 1,
        max: 50,
        step: 0.5,
        log: true,
      },
    ],
  },
  {
    id: 'world',
    title: 'Keep-out zones',
    fields: [
      {
        kind: 'number',
        path: 'world.ceiling',
        label: 'Ceiling',
        unit: 'm',
        min: 0,
        max: 10,
        step: 0.05,
        help: 'A virtual ceiling (0 = none). The drone can fly through it, but it glows and the time spent above is counted.',
      },
      { kind: 'bool', path: 'world.pillar', label: 'Pillar', levels: [2, 3] },
      {
        kind: 'number',
        path: 'world.pillarX',
        label: 'Pillar X',
        unit: 'm',
        min: -10,
        max: 10,
        step: 0.05,
        levels: [2, 3],
        when: (p) => p.world.pillar,
      },
      {
        kind: 'number',
        path: 'world.pillarZ',
        label: 'Pillar Z',
        unit: 'm',
        min: -10,
        max: 10,
        step: 0.05,
        levels: [2, 3],
        when: (p) => p.world.pillar,
      },
      {
        kind: 'number',
        path: 'world.pillarR',
        label: 'Pillar radius',
        unit: 'm',
        min: 0.1,
        max: 3,
        step: 0.05,
        levels: [2, 3],
        when: (p) => p.world.pillar,
      },
    ],
  },
  {
    id: 'mpc',
    title: 'MPC',
    loop: 'alt',
    when: (p) =>
      (p.sim.level === 1 && p.control.l1.kind === 'mpc') ||
      (p.sim.level === 3 && p.control.l3.outer === 'mpc'),
    fields: [
      {
        kind: 'number',
        path: 'control.mpc.horizon',
        label: 'Horizon',
        unit: 's',
        min: 0.1,
        max: 3,
        step: 0.05,
        help: 'How far ahead the controller plans. Longer: more foresight, more computing.',
      },
      {
        kind: 'number',
        path: 'control.mpc.hz',
        label: 'Re-plan rate',
        unit: 'Hz',
        min: 5,
        max: 200,
        step: 1,
        log: true,
        help: 'How often the plan is recomputed; also the prediction step (1/rate).',
      },
      {
        kind: 'number',
        path: 'control.mpc.qPos',
        label: 'Cost of position error',
        min: 0.1,
        max: 1000,
        step: 0.1,
        log: true,
      },
      {
        kind: 'number',
        path: 'control.mpc.qVel',
        label: 'Cost of velocity error',
        min: 0.01,
        max: 100,
        step: 0.01,
        log: true,
      },
      {
        kind: 'number',
        path: 'control.mpc.r',
        label: 'Cost of input',
        min: 0.001,
        max: 10,
        step: 0.001,
        log: true,
      },
      {
        kind: 'number',
        path: 'control.mpc.iterations',
        label: 'QP iterations (cap)',
        min: 1,
        max: 500,
        step: 1,
        log: true,
        help: 'Maximum ADMM iterations per plan. Fewer: cheaper, less optimal.',
      },
      {
        kind: 'number',
        path: 'control.mpc.margin',
        label: 'Ceiling margin',
        unit: 'm',
        min: 0,
        max: 1,
        step: 0.01,
      },
      ...l1Common.map((f): Field => ({ ...f, levels: [1] })),
    ],
  },
  {
    id: 'mppi',
    title: 'MPPI',
    loop: 'pos.x',
    levels: [3],
    when: (p) => p.control.l3.outer === 'mppi',
    fields: [
      {
        kind: 'number',
        path: 'control.mppi.samples',
        label: 'Samples',
        min: 8,
        max: 1024,
        step: 1,
        log: true,
        help: 'How many random futures are tried at every re-plan.',
      },
      {
        kind: 'number',
        path: 'control.mppi.lambda',
        label: 'Temperature λ',
        min: 0.01,
        max: 1000,
        step: 0.01,
        log: true,
        help: 'How the futures are combined: low λ follows the best one (greedy), high λ averages many — and an average of "left of the pillar" and "right of the pillar" is "into the pillar".',
      },
      {
        kind: 'number',
        path: 'control.mppi.sigma',
        label: 'Exploration σ',
        unit: 'm/s²',
        min: 0.1,
        max: 20,
        step: 0.1,
        log: true,
        help: 'How wildly the futures differ from the current plan.',
      },
      {
        kind: 'number',
        path: 'control.mppi.horizon',
        label: 'Horizon',
        unit: 's',
        min: 0.2,
        max: 4,
        step: 0.05,
      },
      {
        kind: 'number',
        path: 'control.mppi.qPos',
        label: 'Cost of position error',
        min: 0.1,
        max: 1000,
        step: 0.1,
        log: true,
      },
      {
        kind: 'number',
        path: 'control.mppi.zoneWeight',
        label: 'Cost of entering a zone',
        min: 0,
        max: 100000,
        step: 1,
        help: 'Added for every second a sampled future spends inside a keep-out zone (plus its margin).',
      },
      {
        kind: 'number',
        path: 'control.mppi.margin',
        label: 'Zone margin',
        unit: 'm',
        min: 0,
        max: 2,
        step: 0.01,
      },
    ],
  },
  {
    id: 'cbf',
    title: 'Safety filter (CBF)',
    levels: [3],
    when: (p) => p.control.l3.safety === 'cbf',
    fields: [
      {
        kind: 'number',
        path: 'control.cbf.gamma',
        label: 'Barrier rate γ',
        unit: '1/s',
        min: 0.2,
        max: 20,
        step: 0.1,
        log: true,
        help: 'How fast the drone may approach a boundary: ḧ + 2γḣ + γ²h ≥ 0. Low: brakes early and gently. High: lets it come close quickly.',
      },
      {
        kind: 'number',
        path: 'control.cbf.margin',
        label: 'Margin',
        unit: 'm',
        min: 0,
        max: 2,
        step: 0.01,
      },
    ],
  },
  {
    id: 'faults',
    title: 'Faults & aerodynamics',
    fields: [
      ...[1, 2, 3, 4].map((i): Field => ({
        kind: 'number',
        path: `drone.motorEfficiency.${i - 1}`,
        label: `Motor ${i} efficiency`,
        min: 0,
        max: 1,
        step: 0.01,
        levels: [1, 3],
        help: 'Fraction of the commanded thrust this motor really produces — a damaged prop or a weak motor. The controller is not told.',
      })),
      {
        kind: 'number',
        path: 'drone.rotorDrag',
        label: 'Rotor drag',
        unit: 's/m',
        min: 0,
        max: 0.05,
        step: 0.001,
        levels: [3],
        help: 'Spinning rotors moving edgewise through the air feel a drag proportional to thrust × in-plane air speed. Real, significant at speed, and not modelled by simple controllers. 0 = off.',
      },
    ],
  },
  {
    id: 'sensors',
    title: 'Sensors',
    fields: [
      {
        kind: 'number',
        path: 'sensors.posNoise',
        label: 'Position noise σ',
        unit: 'm',
        min: 0,
        max: 0.2,
        step: 0.001,
        help: 'Random error on every position reading. Watch what it does to the D term.',
      },
      {
        kind: 'number',
        path: 'sensors.velNoise',
        label: 'Velocity noise σ',
        unit: 'm/s',
        min: 0,
        max: 1,
        step: 0.005,
        levels: [1, 3],
        help: 'Noise of the velocity sensor. In L1 only LQR reads it (without a Kalman filter); PID differentiates the position instead.',
      },
      {
        kind: 'number',
        path: 'sensors.gyroNoise',
        label: 'Gyro noise σ',
        unit: '°/s',
        min: 0,
        max: 50,
        step: 0.1,
        levels: [3],
      },
      {
        kind: 'number',
        path: 'sensors.altBias',
        label: 'Altimeter bias',
        unit: 'm',
        min: -1,
        max: 1,
        step: 0.01,
        help: 'A constant sensor offset. Feedback cannot fix a lying sensor: the drone settles at the wrong height.',
      },
      {
        kind: 'number',
        path: 'sensors.delayMs',
        label: 'Sensor delay',
        unit: 'ms',
        min: 0,
        max: 500,
        step: 1,
        help: 'Transport delay of the measurement. Delay eats stability margin.',
      },
      {
        kind: 'number',
        path: 'sensors.posRateHz',
        label: 'Position sensor rate',
        unit: 'Hz',
        min: 0,
        max: 200,
        step: 1,
        help: 'How often the position sensor (GPS, barometer, motion capture) delivers a new fix; the last one is held in between. 0 = a fresh reading on every controller sample.',
      },
      {
        kind: 'number',
        path: 'sensors.accNoise',
        label: 'Accelerometer noise σ',
        unit: 'm/s²',
        min: 0,
        max: 5,
        step: 0.01,
        levels: [1, 3],
        help: 'Noise of the accelerometer (used by the Kalman filter and acceleration INDI).',
      },
      {
        kind: 'number',
        path: 'sensors.accBias',
        label: 'Accelerometer bias',
        unit: 'm/s²',
        min: -2,
        max: 2,
        step: 0.01,
        levels: [1, 3],
        help: 'A constant accelerometer offset. Integrated twice it would drift away — unless the filter estimates it.',
      },
      {
        kind: 'bool',
        path: 'sensors.posDropout',
        label: 'Altimeter dropout',
        levels: [1],
        help: 'The altimeter stops delivering fixes and the last one is held. A filter must then coast on the accelerometer alone.',
      },
      {
        kind: 'bool',
        path: 'sensors.motorFeedback',
        label: 'Motor telemetry',
        levels: [1, 3],
        help: "Whether the controller can read each motor's speed (RPM telemetry). Used by LQR with the motor-lag state and by INDI; without it they run a model of the motors. It cannot see a damaged prop — only the speed.",
      },
    ],
  },
  {
    id: 'uncertainty',
    title: 'Uncertainty (plant family)',
    levels: [1],
    fields: [
      {
        kind: 'number',
        path: 'uncertainty.massPct',
        label: 'Mass error',
        unit: '± %',
        min: 0,
        max: 60,
        step: 1,
        help: 'How far the real mass may be from the nominal one: a payload, a different battery. Together with the two ranges below it defines a family of drones; robust analysis asks whether the controller works for all of them.',
      },
      {
        kind: 'number',
        path: 'uncertainty.tauFactor',
        label: 'Motor lag factor',
        unit: '×',
        min: 1,
        max: 4,
        step: 0.1,
        help: 'The motor time constant may be this many times shorter or longer than nominal.',
      },
      {
        kind: 'number',
        path: 'uncertainty.delayMs',
        label: 'Extra delay',
        unit: 'ms',
        min: 0,
        max: 80,
        step: 1,
        help: 'Up to this much sensor delay that the design did not count on.',
      },
    ],
  },
  {
    id: 'probe',
    title: 'Probe (frequency response)',
    levels: [1],
    fields: [
      {
        kind: 'select',
        path: 'probe.point',
        label: 'Inject at',
        options: [
          { value: 'none', label: 'off' },
          { value: 'l1.thrust', label: 'the thrust command' },
          { value: 'ref.y', label: 'the altitude setpoint' },
        ],
        help: 'Adds a test signal to the loop. At the thrust command the loop is "broken at the plant input": comparing what the controller sends with what the plant receives gives the open-loop response L. At the setpoint it shows how the drone follows a moving reference.',
      },
      {
        kind: 'select',
        path: 'probe.signal',
        label: 'Signal',
        options: [
          { value: 'sine', label: 'sine' },
          { value: 'chirp', label: 'chirp (rising frequency)' },
        ],
        when: (p) => p.probe.point !== 'none',
      },
      {
        kind: 'number',
        path: 'probe.amp',
        label: 'Amplitude',
        unit: 'N or m',
        min: 0.02,
        max: 3,
        step: 0.01,
        when: (p) => p.probe.point !== 'none',
        help: 'Newtons at the thrust command, metres at the setpoint. Keep it small: a response is only meaningful while the motors stay within their limits.',
      },
      {
        kind: 'number',
        path: 'probe.freqHz',
        label: 'Frequency',
        unit: 'Hz',
        min: 0.05,
        max: 50,
        step: 0.01,
        log: true,
        when: (p) => p.probe.point !== 'none' && p.probe.signal === 'sine',
      },
      {
        kind: 'number',
        path: 'probe.f0Hz',
        label: 'Chirp from',
        unit: 'Hz',
        min: 0.05,
        max: 10,
        step: 0.01,
        log: true,
        when: (p) => p.probe.point !== 'none' && p.probe.signal === 'chirp',
      },
      {
        kind: 'number',
        path: 'probe.f1Hz',
        label: 'Chirp to',
        unit: 'Hz',
        min: 0.5,
        max: 50,
        step: 0.1,
        log: true,
        when: (p) => p.probe.point !== 'none' && p.probe.signal === 'chirp',
      },
      {
        kind: 'number',
        path: 'probe.durationS',
        label: 'Chirp duration',
        unit: 's',
        min: 5,
        max: 120,
        step: 1,
        when: (p) => p.probe.point !== 'none' && p.probe.signal === 'chirp',
      },
    ],
  },
];

export const getIn = (obj: unknown, path: string): unknown =>
  path.split('.').reduce<unknown>((o, k) => (o as Record<string, unknown>)?.[k], obj);

export function setIn<T>(obj: T, path: string, value: unknown): T {
  const [head, ...rest] = path.split('.');
  const o = obj as Record<string, unknown>;
  const next = rest.length ? setIn(o[head!], rest.join('.'), value) : value;
  if (Array.isArray(obj)) {
    const copy = [...obj];
    copy[Number(head)] = next;
    return copy as T;
  }
  return { ...o, [head!]: next } as T;
}
