// The controller arena (lesson II.21). Run with `make bench`; `--write` also updates docs/arena.md.
import { writeFileSync } from 'node:fs';
import { ENTRIES, runArena, SCENARIOS, winners, type ArenaResult } from '@/engine/arena';

const write = process.argv.includes('--write');
const results: ArenaResult[] = [];
const t0 = performance.now();
for (const entry of ENTRIES) {
  for (const sc of SCENARIOS) {
    results.push(runArena(entry, sc));
    process.stdout.write('.');
  }
}
process.stdout.write('\n');

const best = winners(results);
const cell = (r: ArenaResult | undefined, win: boolean) => {
  if (!r) return '—';
  if (r.crashed) return 'crash';
  const v = `${(r.rms * 100).toFixed(1)}`;
  return win ? `**${v}**` : v;
};
const mean = (id: string, f: (r: ArenaResult) => number) => {
  const rows = results.filter((r) => r.entry === id && !r.crashed);
  return rows.reduce((s, r) => s + f(r), 0) / Math.max(rows.length, 1);
};
const cpu = (id: string) => mean(id, (r) => r.cpuUs);
const smooth = (id: string) => mean(id, (r) => r.jitter);
const bestOf = (f: (id: string) => number) =>
  ENTRIES.reduce((a, b) => (f(b.id) < f(a.id) ? b : a)).id;
const bestCpu = bestOf(cpu);
const bestSmooth = bestOf(smooth);
const bold = (v: string, win: boolean) => (win ? `**${v}**` : v);
const lines = [
  `| Controller | ${SCENARIOS.map((s) => s.label).join(' | ')} | Motor jitter, N | µs/step |`,
  `| --- | ${SCENARIOS.map(() => '---:').join(' | ')} | ---: | ---: |`,
  ...ENTRIES.map(
    (e) =>
      `| ${e.label} | ${SCENARIOS.map((s) =>
        cell(
          results.find((r) => r.entry === e.id && r.scenario === s.id),
          best[s.id] === e.id,
        ),
      ).join(
        ' | ',
      )} | ${bold(smooth(e.id).toFixed(3), e.id === bestSmooth)} | ${bold(cpu(e.id).toFixed(1), e.id === bestCpu)} |`,
  ),
];
const table = lines.join('\n');
console.log('\nRMS position error, cm (best in bold). Scenarios:');
for (const s of SCENARIOS) console.log(`  ${s.label}: ${s.about}`);
console.log(`\n${table}\n`);
const wins = new Set([...Object.values(best), bestSmooth, bestCpu]);
const without = ENTRIES.filter((e) => !wins.has(e.id)).map((e) => e.label);
console.log(
  `Winners: ${[...wins].length} different controllers win the ${SCENARIOS.length + 2} columns.`,
);
if (without.length) console.log(`No win: ${without.join(', ')}.`);
console.log(
  `(${((performance.now() - t0) / 1000).toFixed(0)} s; µs/step is wall-clock and machine-dependent.)`,
);

if (write) {
  const doc = `# The arena — measured results

Generated by \`make bench\` (scripts/bench.ts → src/engine/arena.ts) on ${new Date().toISOString().slice(0, 10)}.
Every controller flies every scenario on the same seeded conditions. Scenario columns: RMS 3D
position error in **cm** from the scenario's start of measurement. *Motor jitter*: RMS change of
the total thrust between 200 Hz samples, averaged over the scenarios — how hard the motors work.
*µs/step*: wall-clock cost per 1 ms physics step on the machine that ran it. Best per column in
bold.

${SCENARIOS.map((s) => `- **${s.label}** — ${s.about}.`).join('\n')}

${table}

See lesson II.21 "The grand comparison" and [beyond-pid.md](beyond-pid.md).
`;
  writeFileSync(new URL('../docs/arena.md', import.meta.url), doc);
  console.log('Wrote docs/arena.md');
}
