// The robustness report card (lesson III.30). Run with `make report`; `--write` also updates
// docs/report.md.
import { writeFileSync } from 'node:fs';
import {
  CARD_RUNS,
  meetsMargins,
  REPORT_ENTRIES,
  ReportCard,
  REQUIRED,
  type ReportRow,
} from '@/analysis/report';

const write = process.argv.includes('--write');
const t0 = performance.now();
const rows: ReportRow[] = [];
for (const e of REPORT_ENTRIES) {
  const card = new ReportCard([e]);
  while (!card.advance(1_000_000));
  rows.push(card.rows[0]!);
  process.stdout.write('.');
}
process.stdout.write('\n');

const fmt = (v: number, d = 0) => (Number.isFinite(v) ? v.toFixed(d) : '∞');
const table = (level: 1 | 3) => {
  const mine = rows.filter((r) => r.level === level);
  const best = mine.filter((r) => !r.crashed).reduce((a, b) => (b.rms < a.rms ? b : a)).id;
  const flag = (bad: boolean, v: string) => (bad ? `**${v}** ▲` : v);
  return [
    `| ${level === 1 ? 'L1 altitude' : 'L3 quadrotor'} | PM, ° | GM, dB | Delay margin, ms | ‖S‖∞ | Monte Carlo (≥ rate, 95 %) | RMS in gusts, cm |`,
    '| --- | ---: | ---: | ---: | ---: | ---: | ---: |',
    ...mine.map(
      (r) =>
        `| ${r.label}${meetsMargins(r) ? '' : ' ▲'} | ${r.linear ? `${flag(r.pmDeg < REQUIRED.pmDeg, fmt(r.pmDeg, 1))} | ${flag(r.gmDb < REQUIRED.gmDb, fmt(r.gmDb, 1))} | ${fmt(r.delayMs)} | ${r.ms.toFixed(2)}` : '— | — | — | —'} | ${r.passed}/${r.runs} (≥ ${(r.bound * 100).toFixed(1)} %) | ${r.crashed ? 'crash' : r.id === best ? `**${(r.rms * 100).toFixed(1)}**` : (r.rms * 100).toFixed(1)} |`,
    ),
  ].join('\n');
};
const out = `${table(1)}\n\n${table(3)}`;
console.log(`\n${out}\n`);
console.log(`(${((performance.now() - t0) / 1000).toFixed(0)} s)`);

if (write) {
  const doc = `# The robustness report card — measured results

Generated by \`make report\` (scripts/report.ts → src/analysis/report.ts) on ${new Date().toISOString().slice(0, 10)}.
Every number is measured on the simulator, none is modelled:

- **PM, GM, delay margin, ‖S‖∞** — from a probe sweep with the loop broken at the plant input:
  the thrust command for L1, the roll torque for L3. GM is the smaller of the margins up and
  down. ▲ marks a controller below the classical requirement of ${REQUIRED.gmDb} dB and ${REQUIRED.pmDeg}° (values in
  bold). A dash: the sweep found no consistent linear loop (a negative margin on a controller
  that flies), so no margin can be stated.
- **Monte Carlo** — ${CARD_RUNS} flights each. L1: members of the plant family of lesson III.11 (mass
  ±30 %, motor lag ×0.5–2, up to 20 ms of extra delay), judged on stability. L3: the dispersions of
  lesson III.29 (mass, motor lag, sensor delay, gyro bias, wind) in gusty hover, judged on crash
  or a body rate above 300 °/s. With ${CARD_RUNS} clean flights the bound is 94 %.
- **RMS in gusts** — one flight on a fixed seed: Part I's gust challenge for L1 (altitude
  error), the arena's gust scenario for L3 (position error). Best in bold.

${out}

See lesson III.30 "The robustness report card" and [arena.md](arena.md).
`;
  writeFileSync(new URL('../docs/report.md', import.meta.url), doc);
  console.log('Wrote docs/report.md');
}
